[toolchain]

[features]
resolution = true
skip-lint = false
seeds = false

[programs.localnet]
nft = "4kwcURKome7NkYanznMuPV7M3qZbin67qb2YD4tZBzKA"
[programs.devnet]
nft = "4kwcURKome7NkYanznMuPV7M3qZbin67qb2YD4tZBzKA"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
#cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

#https://github.com/solana-developers/program-examples/blob/main/tokens/spl-token-minter/anchor/Anchor.toml
[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[test.validator]
bind_address = "0.0.0.0"
url = "https://api.mainnet-beta.solana.com"
ledger = ".anchor/test-ledger"
rpc_port = 8899

[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
